springdoc:
  api-docs:
    enabled: true # 开启OpenApi接口
    path: /v3/api-docs  # 自定义路径，默认为 "/v3/api-docs"
  swagger-ui:
    enabled: true # 开启swagger界面，依赖OpenApi，需要OpenApi同时开启
    path: /swagger-ui/index.html # 自定义路径，默认为"/swagger-ui/index.html"
  writer-with-default-pretty-printer: true
knife4j:
  enable: true
  setting:
    language: zh_cn
  production: false
  basic:
    enable: false
nbdeyy:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: hospital_appointment
    username: root
    password: root
  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: ALIBABA_CAPTCHA_ACCESS_KEY_ID
    access-key-secret: ALIBABA_CAPTCHA_ACCESS_KEY_SECRET
    bucket-name: nbdeyy-hospital-appointment
  redis:
    host: localhost
    port: 6379
    database: 10
  alicaptcha:
    access-key-id: ALIBABA_CAPTCHA_ACCESS_KEY_ID
    access-key-secret: ALIBABA_CAPTCHA_ACCESS_KEY_SECRET
  rsa:
    key:
      rotation:
        interval: 168
        expire-days: 30

