server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: ${nbdeyy.datasource.driver-class-name}
    url: jdbc:mysql://${nbdeyy.datasource.host}:${nbdeyy.datasource.port}/${nbdeyy.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${nbdeyy.datasource.username}
    password: ${nbdeyy.datasource.password}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  data:
    redis:
      host: ${nbdeyy.redis.host}
      port: ${nbdeyy.redis.port}
      database: ${nbdeyy.redis.database}


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.nbdeyy.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      nbdeyy:
        mapper: debug
        service: info
        controller: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n"
nbdeyy:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: nbdeyy-admin
    # 设置jwt过期时间
    admin-ttl: 72000000
    # 设置前端传递过来的令牌名称
    admin-token-name: Token
    # 设置jwt签名加密时使用的秘钥
    user-secret-key: nbdeyy-user
    # 设置jwt过期时间
    user-ttl: 7200000
    # 设置前端传递过来的令牌名称
    user-token-name: Authorization
  alioss:
    endpoint: ${nbdeyy.alioss.endpoint}
    access-key-id: ${nbdeyy.alioss.access-key-id}
    access-key-secret: ${nbdeyy.alioss.access-key-secret}
    bucket-name: ${nbdeyy.alioss.bucket-name}
  alicaptcha:
    access-key-id: ${nbdeyy.alicaptcha.access-key-id}
    access-key-secret: ${nbdeyy.alicaptcha.access-key-secret}
  rsa:
    key:
      rotation:
        interval: ${nbdeyy.rsa.key.rotation.interval}
        expire-days: ${nbdeyy.rsa.key.rotation.expire-days}